AWSTemplateFormatVersion: 2010-09-09

Description: A Cloudformation template for provisioning a VPC.

Parameters:
  CidrBlock:
    Type: String
    Description: 'The CIDR block covered by the VPC. For example: "10.0.0.0/16"'
  Environment:
    Type: String
    Description: The name of the environment represented by the VPC

Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref CidrBlock
      EnableDnsHostnames: true
      Tags:
        - Key: Environment
          Value: !Ref Environment

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Environment
          Value: !Ref Environment

  VpcGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref Vpc
      InternetGatewayId: !Ref InternetGateway

  PublicRoutes:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-public-routes

  PublicRouteDefault:
    Type: AWS::EC2::Route
    DependsOn: VpcGatewayAttachment
    Properties:
      GatewayId: !Ref InternetGateway
      DestinationCidrBlock: '0.0.0.0/0'
      
#  PrivateRoutes:
#    Type: AWS::EC2::RouteTable
#    Properties:
#      VpcId: !Ref Vpc
#      Tags:
#        - Key: Name
#          Value: !Sub ${Environment}-private-routes

Outputs:
  VpcId:
    Description: The VPC ID
    Value: !Ref Vpc
