services:
  - docker
script:
  - cd blueprints
  - make all
deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && cd blueprints && make tag push all
  on:
    branch: master
