language: python

services:
  - docker

script:
  - cd blueprints
  - TAGS="latest,$TRAVIS_TAG" make all tag

deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && cd blueprints && make tag push all
  on:
    branch: master
