#cloud-config
#yum_repos:
#  epel-testing:
#    baseurl: http://dl.fedoraproject.org/pub/epel/7/$basearch
#    enabled: true
#    failovermethod: priority
#    gpgcheck: true
#    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL
#    name: Extra Packages for Enterprise Linux 7 - Testing

packages:
#  - fail2ban
#  - ntpdate
  - chrony

timezone: Australia/Melbourne

#ntp:
#  enabled: true
#  servers:
#    - 0.au.pool.ntp.org
#    - 1.au.pool.ntp.org
#    - 2.au.pool.ntp.org
#    - 3.au.pool.ntp.org

users:
  - name: ${AuthorizedUserName}
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ${AuthorizedUserSSHKey}

bootcmd:
  - shutdown -P +60 System will shutdown in 60 minutes

runcmd:
  - "printf '\nClientAliveInterval 100\nClientAliveCountMax 0' >> /etc/ssh/sshd_config"
  - service sshd restart
  - systemctl start chronyd && systemctl enable chronyd

power_state:
  timeout: 120
  delay: "${ShutdownDelay}"
  message: System will shutdown in ${ShutdownDelay} minutes
  mode: poweroff
