moduledir 'thirdparty'

mod 'gene1wood-credstash'
mod 'stankevich-python', '1.9.8'
mod 'stahnma-epel'
mod 'puppetlabs-stdlib'
mod 'puppetlabs-rancher'
mod 'puppetlabs-apt', '3.0.0'
mod 'puppetlabs-translate'
mod 'garethr-docker', '5.3.0'
mod 'puppet-nginx'
mod 'puppetlabs-concat'
mod 'puppet-letsencrypt'
mod 'puppetlabs-inifile'
mod 'puppetlabs-vcsrepo'
mod 'puppetlabs/ntp', :latest

mod 'attachmentgenie-ufw', :git => 'https://github.com/attachmentgenie/attachmentgenie-ufw.git'
