AWSTemplateFormatVersion: 2010-09-09

Description: A Cloudformation template for provisioning an NGINX reverse proxy stack.

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC used to provision cluster
  ImageId:
    Type: AWS::EC2::Image::Id
    Description: EC2 AMI ID
  InstanceType:
    Type: String
    Description: EC2 instance type
  KeyPair:
    Type: String
    Description: The name of the keypair for accessing the host
#  BastionSecurityGroupId:
#    Type: AWS::EC2::SecurityGroup::Id
#    Description: Subnet to deploy into
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet to deploy into
  Environment:
    Type: String
    Description: The name of the environment to associate with
  UserData:
    Type: String
    Description: Bootstrap configuration to run on EC2 instance

Resources:
  ReverseProxySG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: ReverseProxySG
      GroupDescription: Security group for ReverseProxy
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
#        - IpProtocol: tcp
#          FromPort: 22
#          ToPort: 22
#          SourceSecurityGroupId: !Ref BastionSecurityGroupId
      Tags:
        - Key: Name
          Value: ReverseProxySG

  ReverseProxyEC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - ec2.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM

  ReverseProxyInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref ReverseProxyEC2Role

  ReverseProxyInstance:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref ReverseProxyInstanceProfile
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
#      KeyName: !Ref KeyPair
      Monitoring: true
      SecurityGroupIds:
        - !Ref ReverseProxySG
#      SsmAssociations:
#        - SSMAssociation
      SubnetId: !Ref SubnetId
      Tags:
        - Key: Environment
          Value: !Ref Environment
      UserData: !Ref UserData

#  ReverseProxyDashboard:
#    Type: AWS::CloudWatch::Dashboard
#    Properties:
#      DashboardName: ReverseProxy
#      DashboardBody: !Sub |
#        {}
#
#Outputs:
