AWSTemplateFormatVersion: 2010-09-09

Description: A Cloudformation template for provisioning an Aurora cluster.

Parameters:
  AvailabilityZones:
    Type: List<AWS::EC2::AvailabilityZone::Name>

Resources:
  'Fn::Transform':
    Name: 'AWS::Include'
    Description: Import DBCluster ParameterGroup for the specified engine
    Parameters:
      Location: !Sub ${BucketUrl}/${Engine}_${EngineVersion}-params.yml

  ClusterSubnetGroup:

  ClusterSecurityGroup:

  DatabaseCluster:

  PrimaryInstance:

  PrimaryInstanceCPUAlarm:

  PrimaryInstancesMemoryAlarm:

  PrimaryInstanceEndpoint:

  ReplicaInstance:

  ReplicaInstanceCPUAlarm:

  ReplicaInstancesMemoryAlarm:

  ReplicaInstanceEndpoint:

  ClusterStartSchedule:

  ClusterStartSchedulePermission:

  ClusterStopSchedule:

  ClusterStopSchedulePermission:

  ClusterSnapshotSchedule:

  ClusterSnapshotSchedulePermission:
