#cloud-config
packages:
  - fail2ban
  - unattended-upgrades
  - ntpdate

timezone: Australia/Melbourne

ntp:
  enabled: true
  servers:
    - 0.au.pool.ntp.org
    - 1.au.pool.ntp.org
    - 2.au.pool.ntp.org
    - 3.au.pool.ntp.org

users:
  - name: ${AuthorizedUserName}
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ${AuthorizedUserSSHKey}

runcmd:
  - "printf '\nClientAliveInterval 100\nClientAliveCountMax 0' >> /etc/ssh/sshd_config"
  - service ssh restart
  - "wget --header='X-Papertrail-Token: QHS89ESNb9Q0OGPK9Hu2' https://papertrailapp.com/destinations/2465304/setup.sh"
  - bash setup.sh

power_state:
  timeout: 120
  delay: "${ShutdownDelay}"
  message: System will shutdown in ${ShutdownDelay} minutes
  mode: poweroff
