AsgLaunchConfig:
  Type: AWS::AutoScaling::LaunchConfiguration
  Properties:
    ImageId: !Ref ImageId
    InstanceType: !Ref InstanceType
    InstanceMonitoring: true
    IamInstanceProfile: !Ref AsgInstanceProfile
    SecurityGroups:
      - !Ref InstanceSG
    AssociatePublicIpAddress: false
    UserData:
      Fn::Base64: !Sub |
        #!/bin/bash
        echo ECS_CLUSTER=${EcsCluster} >> /etc/ecs/ecs.config

AsgSpotLaunchConfig:
  Type: AWS::AutoScaling::LaunchConfiguration
  Properties:
    ImageId: !Ref ImageId
    InstanceType: !Ref InstanceType
    SpotPrice: !Ref SpotPrice
    InstanceMonitoring: true
    IamInstanceProfile: !Ref EcsInstanceProfile
    SecurityGroups:
      - !Ref InstanceSG
    AssociatePublicIpAddress: false
    UserData:
      Fn::Base64: !Sub |
        #!/bin/bash
        echo ECS_CLUSTER=${EcsCluster} >> /etc/ecs/ecs.config
