EcsLaunchConfig:
  Type: AWS::AutoScaling::LaunchConfiguration
  Properties:
    ImageId: !Ref ImageId
    InstanceType: !Ref InstanceType
    InstanceMonitoring: true
    IamInstanceProfile: !Ref EcsInstanceProfile
    SecurityGroups:
      - !Ref InstanceSG
    AssociatePublicIpAddress: false
    UserData:
      Fn::Base64: !Sub |
        <powershell>
        Import-Module ECSTools
        Initialise-ECSAgent -Cluster '${EcsCluster}' -EnableTaskIAMRole
        </powershell>

EcsSpotLaunchConfig:
  Type: AWS::AutoScaling::LaunchConfiguration
  Properties:
    ImageId: !Ref ImageId
    InstanceType: !Ref InstanceType
    SpotPrice: !Ref SpotPrice
    InstanceMonitoring: true
    IamInstanceProfile: !Ref EcsInstanceProfile
    SecurityGroups:
      - !Ref InstanceSG
    AssociatePublicIpAddress: false
    UserData:
      Fn::Base64: !Sub |
        <powershell>
        Import-Module ECSTools
        Initialise-ECSAgent -Cluster '${EcsCluster}' -EnableTaskIAMRole
        </powershell>
