#cloud-config
packages:
  - apt-transport-https
  - ca-certificates
  - gnupg-agent
  - software-properties-common
  - unattended-upgrades
  - curl
  - ntpdate
  - python-pip
  - zip
  - openjdk-11-jdk

timezone: Australia/Melbourne

ntp:
  enabled: true
  servers:
    - 0.au.pool.ntp.org
    - 1.au.pool.ntp.org
    - 2.au.pool.ntp.org
    - 3.au.pool.ntp.org

users:
  - name: ${AuthorizedUserName}
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ${AuthorizedUserSSHKey}

#groups:
#  - docker: ['${AuthorizedUserName}']

write_files:
  - path: /etc/update-motd.d/99-unauthorised-access
    permissions: "0755"
    owner: "root"
    content: |
      echo 'UNAUTHORIZED ACCESS TO THIS DEVICE IS PROHIBITED

      You must have explicit, authorized permission to access or configure this device. Unauthorized attempts and
      actions to access or use this system may result in civil and/or criminal penalties. All activities performed on
      this device are logged and monitored.'

runcmd:
  # SSH
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -i -e '/^PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
  - restart ssh
  # Docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update && apt-get install -y docker-ce docker-ce-cli containerd.io
  - usermod -aG docker ${AuthorizedUserName}
  - pip install docker-compose
  # sdkman
  - curl -s "https://get.sdkman.io" | bash
  # Papertrail
  - "wget --header='X-Papertrail-Token: QHS89ESNb9Q0OGPK9Hu2' https://papertrailapp.com/destinations/2465304/setup.sh"
  - bash setup.sh
  - curl -O https://github.com/papertrail/remote_syslog2/releases/download/v0.20/remote-syslog2_0.20_amd64.deb
  - dpkg --install remote-syslog2_0.20_amd64.deb
  - remote_syslog
