#cloud-config
yum_repos:
  epel-testing:
    baseurl: http://dl.fedoraproject.org/pub/epel/7$basearch
    enabled: true
    failovermethod: priority
    gpgcheck: true
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL
    name: Extra Packages for Enterprise Linux 7 - Testing

packages:
  - nginx
  - curl
  - ntpdate
  - python
  - python2-certbot-nginx

timezone: Australia/Melbourne

ntp:
  enabled: true
  servers:
    - 0.au.pool.ntp.org
    - 1.au.pool.ntp.org
    - 2.au.pool.ntp.org
    - 3.au.pool.ntp.org

write_files:
  - content: |
      server {
        listen 127.0.0.1:80;
        server_name 127.0.0.1;
        location /nginx_status {
          stub_status on;
          allow 127.0.0.1;
          deny all;
        }
      }
    path: /etc/nginx/conf.d/stub_status.conf
  - content: |
      files:
        - /var/log/nginx/access.log
        - /var/log/nginx/error.log
      destination:
        host: ${PapertrailHost}
        port: ${PapertrailPort}
        protocol: tls
      pid_file: /var/run/remote_syslog.pid
    path: /etc/log_files.yml

runcmd:
  - export API_KEY="${NginxAmplifyKey}"
  - curl -L https://github.com/nginxinc/nginx-amplify-agent/raw/master/packages/install.sh | bash
  - "wget --header='X-Papertrail-Token: QHS89ESNb9Q0OGPK9Hu2' https://papertrailapp.com/destinations/2465304/setup.sh"
  - bash setup.sh
  - curl -O https://github.com/papertrail/remote_syslog2/releases/download/v0.20/remote-syslog2_0.20_amd64.deb
  - dpkg --install remote-syslog2_0.20_amd64.deb
  - remote_syslog
