name: Docker Image CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build aws/ecr
      run: cd aws-ecr && DOCKER_TAGS=$(date +%s),latest make build
    - name: Build aws/ecs
      run: cd aws-ecs && DOCKER_TAGS=$(date +%s),latest make build
