#cloud-config
packages:
#  - ntpdate
  - java
  - nfs-utils
  - chrony

timezone: Australia/Melbourne

#ntp:
#  enabled: true
#  servers:
#    - 0.au.pool.ntp.org
#    - 1.au.pool.ntp.org
#    - 2.au.pool.ntp.org
#    - 3.au.pool.ntp.org

users:
  - name: ${AuthorizedUserName}
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ${AuthorizedUserSSHKey}
  - name: apachesling
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']

write_files:
  - content: |
      [Unit]
      Description=Apache Sling

      [Service]
      User=apachesling
      WorkingDirectory=/opt/sling
      ExecStart=/usr/bin/java $JAVA_OPTS -jar org.apache.sling.starter.jar $SLING_OPTS
      SuccessExitStatus=143
      TimeoutStopSec=10
      Restart=on-failure
      RestartSec=5

      [Install]
      WantedBy=multi-user.target
    path: /etc/systemd/system/apachesling.service
  - content: |
      {
        "logs": {
            "logs_collected": {
                "files": {
                    "collect_list": [
                        {
                            "file_path": "/opt/sling/sling/logs/access.log",
                            "log_group_name": "${SlingHostname}-access-log",
                            "log_stream_name": "{instance_id}"
                        },
                        {
                            "file_path": "/opt/sling/sling/logs/request.log",
                            "log_group_name": "${SlingHostname}-request-log",
                            "log_stream_name": "{instance_id}"
                        },
                        {
                            "file_path": "/opt/sling/sling/logs/error.log",
                            "log_group_name": "${SlingHostname}-error-log",
                            "log_stream_name": "{instance_id}"
                        }
                    ]
                }
            }
        },
        "metrics": {
            "append_dimensions": {
                "AutoScalingGroupName": "$${aws:AutoScalingGroupName}",
                "ImageId": "$${aws:ImageId}",
                "InstanceId": "$${aws:InstanceId}",
                "InstanceType": "$${aws:InstanceType}"
            },
            "metrics_collected": {
                "mem": {
                    "measurement": [
                        "mem_used_percent"
                    ],
                    "metrics_collection_interval": 60
                },
                "swap": {
                    "measurement": [
                        "swap_used_percent"
                    ],
                    "metrics_collection_interval": 60
                }
            }
        }
      }
    path: /opt/aws/amazon-cloudwatch-agent/etc/config.json

mounts:
  - [ swap, none, swap, sw, 0, 0]

swap:
  filename: /var/cache/swap/swapfile
  size: auto
  maxsize: 2147483648

runcmd:
  # Configure SSH
  - "printf '\nClientAliveInterval 100\nClientAliveCountMax 0' >> /etc/ssh/sshd_config"
  - service sshd restart
  - systemctl start chronyd && systemctl enable chronyd
  #  Cloudwatch Agent install
  - curl -O https://s3.amazonaws.com/amazoncloudwatch-agent/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm
  - rpm -U amazon-cloudwatch-agent.rpm
  - /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/opt/aws/amazon-cloudwatch-agent/etc/config.json -s
  #  Apache Sling install
  - mkdir -p /opt/sling
  - wget https://repo1.maven.org/maven2/org/apache/sling/org.apache.sling.starter/${SlingVersion}/org.apache.sling.starter-${SlingVersion}.jar -O /opt/sling/org.apache.sling.starter.jar
#  - mkdir /opt/sling/sling/startup/20/
#  - wget https://repo1.maven.org/maven2/org/mnode/whistlepost/whistlepost-app/1.1.4/whistlepost-app-1.1.4.jar -O /opt/sling/sling/startup/20/
#  - wget https://repo1.maven.org/maven2/org/mnode/whistlepost/whistlepost-config/1.1.4/whistlepost-config-1.1.4.jar -O /opt/sling/sling/startup/20/
#  - wget https://repo1.maven.org/maven2/org/mnode/whistlepost/whistlepost-content/1.1.4/whistlepost-content-1.1.4.jar -O /opt/sling/sling/startup/20/
  - chown -R apachesling:apachesling /opt/sling
  - systemctl enable apachesling.service
  - systemctl start apachesling.service
